version: '3'
services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: mongodb://database:27017/mydatabase

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
      harsh
